__all__ = [
    'DASH_RED', 'DASH_YELLOW', 'DASH_BLUE', 'DASH_GREEN', 'DASH_PURPLE',
    'DASH_RED_LIGHT', 'DASH_YELLOW_LIGHT', 'DASH_BLUE_LIGHT', 'DASH_GREEN_LIGHT', 'DASH_PURPLE_LIGHT',
    'DASH_RED_DARK', 'DASH_YELLOW_DARK', 'DASH_BLUE_DARK', 'DASH_GREEN_DARK', 'DASH_PURPLE_DARK',
    'DASH_GREY_LIGHT'
]

DASH_RED = '#FA897B'
DASH_YELLOW = '#FFDD94'
DASH_BLUE = '#86E3CE'
DASH_GREEN = '#D0E6A5'
DASH_PURPLE = '#CCABDB'

DASH_RED_LIGHT = '#FBBAB2'
DASH_YELLOW_LIGHT = '#F7EACE'
DASH_BLUE_LIGHT = '#BDFFF0'
DASH_GREEN_LIGHT = '#E2EEC9'
DASH_PURPLE_LIGHT = '#E9DAF0'

DASH_RED_DARK = '#F97362'
DASH_YELLOW_DARK = '#EEC367'
DASH_BLUE_DARK = '#7DD2BF'
DASH_GREEN_DARK = '#BFE17C'
DASH_PURPLE_DARK = '#B48BC8'

DASH_GREY_LIGHT = '#F0F0F0'
